Fixes bug in devel/query
DFHack/scripts pull request #336
Opened 2021-09-20 02:55 UTC by cppcooper

Fixes a bug in devel/query caused by not escaping brackets in the starting path. The problem is of redundantly printing the parent path of a field, which thankfully only happens once due to the implementation of printing parents.
example:
```
[DFHack]# devel/query -table df.global.world.history.figures[256]
df.global.world.history.figures[256]: <historical_figure: 0x7fff24eaa900>
| df
| | global
| | | world
| | | | history
| | | | | figures[256]
| profession: ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ 102
| race: ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ 798
| caste: ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~  0
| sex: ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~  -1
| orientation_flags: ~ ~ ~ ~ ~ ~ ~ ~ ~ ~  <orientation_flags: 0x7fff24eaa908>
```

2022-03-08 05:25 UTC, myk002 requested changes
Looks good. I like your technique for escaping all the special chars.

Could you remove the commented out print lines and add a changelog entry?

2022-03-08 21:04 UTC, cppcooper commented
> Looks good. I like your technique for escaping all the special chars.
> 
> Could you remove the commented out print lines and add a changelog entry?

I do believe that pattern was crafted by someone in the dfhack discord, possibly TPH.

I'll take a look at the changelog the same time I get to the EM pr

2022-03-11 21:26 UTC, cppcooper commented
Added the changelog entry and removed the temp debug lines. If you want me to resolve the changelog conflicts lmk

2022-03-23 21:59 UTC, myk002 approved these changes

2022-03-23 22:05 UTC, merged